# Form implementation generated from reading ui file 'Forms_UI/QLIST.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(259, 207)
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        Dialog.setFont(font)
        Dialog.setWindowTitle("LIST FORM")
        Dialog.setToolTip("")
        Dialog.setStatusTip("")
        Dialog.setWhatsThis("")
        Dialog.setAccessibleName("")
        Dialog.setAccessibleDescription("")
        Dialog.setWindowFilePath("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lst = QtWidgets.QListWidget(parent=Dialog)
        self.lst.setMinimumSize(QtCore.QSize(221, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lst.setFont(font)
        self.lst.setToolTip("")
        self.lst.setStatusTip("")
        self.lst.setWhatsThis("")
        self.lst.setAccessibleName("")
        self.lst.setAccessibleDescription("")
        self.lst.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.lst.setAlternatingRowColors(True)
        self.lst.setProperty("isWrapping", False)
        self.lst.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.lst.setUniformItemSizes(False)
        self.lst.setWordWrap(False)
        self.lst.setSelectionRectVisible(False)
        self.lst.setObjectName("lst")
        self.gridLayout.addWidget(self.lst, 0, 0, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass
