# Form implementation generated from reading ui file 'Forms_UI/QCALENDAR.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 270)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("CALENDAR")
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setToolTip("")
        self.centralwidget.setStatusTip("")
        self.centralwidget.setWhatsThis("")
        self.centralwidget.setAccessibleName("")
        self.centralwidget.setAccessibleDescription("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_run = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_run.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_run.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(15)
        self.btn_run.setFont(font)
        self.btn_run.setToolTip("")
        self.btn_run.setStatusTip("")
        self.btn_run.setWhatsThis("")
        self.btn_run.setAccessibleName("")
        self.btn_run.setAccessibleDescription("")
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 2, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setToolTip("")
        self.calendarWidget.setStatusTip("")
        self.calendarWidget.setWhatsThis("")
        self.calendarWidget.setAccessibleName("")
        self.calendarWidget.setAccessibleDescription("")
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btn_run.setText(_translate("MainWindow", "ENTER DATE"))
