# Form implementation generated from reading ui file 'Forms_UI/QLICENSE.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 200)
        MainWindow.setWindowTitle("LICENSE")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn.setEnabled(True)
        self.btn.setMinimumSize(QtCore.QSize(0, 60))
        self.btn.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(25)
        font.setBold(True)
        self.btn.setFont(font)
        self.btn.setToolTip("")
        self.btn.setStatusTip("")
        self.btn.setWhatsThis("")
        self.btn.setAccessibleName("")
        self.btn.setAccessibleDescription("")
        self.btn.setText("OK")
        self.btn.setIconSize(QtCore.QSize(30, 30))
        self.btn.setShortcut("")
        self.btn.setObjectName("btn")
        self.gridLayout.addWidget(self.btn, 1, 0, 1, 1)
        self.tx_preview = QtWidgets.QTextEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.tx_preview.setFont(font)
        self.tx_preview.setWhatsThis("")
        self.tx_preview.setAccessibleName("")
        self.tx_preview.setAccessibleDescription("")
        self.tx_preview.setDocumentTitle("")
        self.tx_preview.setMarkdown("")
        self.tx_preview.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\';\"><br /></p></body></html>")
        self.tx_preview.setPlaceholderText("")
        self.tx_preview.setObjectName("tx_preview")
        self.gridLayout.addWidget(self.tx_preview, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass
