# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QACQUISITIONS.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QDialog,
    QGridLayout, QGroupBox, QHeaderView, QLineEdit,
    QPushButton, QSizePolicy, QTableWidget, QTableWidgetItem,
    QVBoxLayout, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(388, 477)
        font = QFont()
        font.setFamilies([u"Tahoma"])
        Dialog.setFont(font)
#if QT_CONFIG(whatsthis)
        Dialog.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        Dialog.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        Dialog.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tx_info = QLineEdit(Dialog)
        self.tx_info.setObjectName(u"tx_info")
        self.tx_info.setMinimumSize(QSize(0, 27))
        self.tx_info.setMaximumSize(QSize(16777215, 27))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(10)
        font1.setBold(False)
        self.tx_info.setFont(font1)
#if QT_CONFIG(tooltip)
        self.tx_info.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tx_info.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.tx_info.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tx_info.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tx_info.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tx_info.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.tx_info.setInputMask(u"")
        self.tx_info.setText(u"")
        self.tx_info.setFrame(True)
        self.tx_info.setAlignment(Qt.AlignCenter)
        self.tx_info.setReadOnly(True)
        self.tx_info.setPlaceholderText(u"")

        self.verticalLayout.addWidget(self.tx_info)

        self.grp_value = QGroupBox(Dialog)
        self.grp_value.setObjectName(u"grp_value")
        self.grp_value.setMinimumSize(QSize(0, 170))
        self.grp_value.setMaximumSize(QSize(16777215, 170))
        font2 = QFont()
        font2.setFamilies([u"Tahoma"])
        font2.setPointSize(7)
        self.grp_value.setFont(font2)
#if QT_CONFIG(tooltip)
        self.grp_value.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.grp_value.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.grp_value.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.grp_value.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.grp_value.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.grp_value.setTitle(u"TYPE / VALUE / UNIT")
        self.gridLayout_3 = QGridLayout(self.grp_value)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tx_value = QLineEdit(self.grp_value)
        self.tx_value.setObjectName(u"tx_value")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.tx_value.sizePolicy().hasHeightForWidth())
        self.tx_value.setSizePolicy(sizePolicy)
        self.tx_value.setMinimumSize(QSize(0, 45))
        font3 = QFont()
        font3.setFamilies([u"Consolas"])
        font3.setPointSize(16)
        self.tx_value.setFont(font3)
#if QT_CONFIG(tooltip)
        self.tx_value.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tx_value.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.tx_value.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tx_value.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tx_value.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tx_value.setLayoutDirection(Qt.LeftToRight)
        self.tx_value.setInputMask(u"")
        self.tx_value.setText(u"")
        self.tx_value.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.tx_value.setPlaceholderText(u"")

        self.gridLayout_3.addWidget(self.tx_value, 1, 0, 1, 1)

        self.cb_type = QComboBox(self.grp_value)
        self.cb_type.setObjectName(u"cb_type")
        self.cb_type.setMinimumSize(QSize(300, 30))
        self.cb_type.setMaximumSize(QSize(2000000, 30))
        font4 = QFont()
        font4.setFamilies([u"Consolas"])
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setItalic(False)
        self.cb_type.setFont(font4)
#if QT_CONFIG(tooltip)
        self.cb_type.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.cb_type.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.cb_type.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.cb_type.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.cb_type.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.cb_type.setLayoutDirection(Qt.LeftToRight)
        self.cb_type.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.cb_type.setCurrentText(u"")

        self.gridLayout_3.addWidget(self.cb_type, 0, 0, 1, 2)

        self.btn_addvalue = QPushButton(self.grp_value)
        self.btn_addvalue.setObjectName(u"btn_addvalue")
        self.btn_addvalue.setMinimumSize(QSize(350, 40))
        self.btn_addvalue.setMaximumSize(QSize(16777215, 40))
        font5 = QFont()
        font5.setFamilies([u"Tahoma"])
        font5.setPointSize(12)
        font5.setBold(True)
        self.btn_addvalue.setFont(font5)
#if QT_CONFIG(tooltip)
        self.btn_addvalue.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_addvalue.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_addvalue.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_addvalue.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_addvalue.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_addvalue.setText(u"ADD VALUE")
#if QT_CONFIG(shortcut)
        self.btn_addvalue.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout_3.addWidget(self.btn_addvalue, 2, 0, 1, 2)

        self.cb_units = QComboBox(self.grp_value)
        self.cb_units.setObjectName(u"cb_units")
        self.cb_units.setMinimumSize(QSize(120, 45))
        self.cb_units.setMaximumSize(QSize(120, 45))
        font6 = QFont()
        font6.setFamilies([u"Consolas"])
        font6.setPointSize(16)
        font6.setBold(False)
        font6.setItalic(False)
        self.cb_units.setFont(font6)
#if QT_CONFIG(tooltip)
        self.cb_units.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.cb_units.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.cb_units.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.cb_units.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.cb_units.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.cb_units.setEditable(False)
        self.cb_units.setCurrentText(u"")
        self.cb_units.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.cb_units.setDuplicatesEnabled(True)
        self.cb_units.setFrame(True)

        self.gridLayout_3.addWidget(self.cb_units, 1, 1, 1, 1)


        self.verticalLayout.addWidget(self.grp_value)

        self.grp_list = QGroupBox(Dialog)
        self.grp_list.setObjectName(u"grp_list")
        self.grp_list.setMinimumSize(QSize(0, 250))
        self.grp_list.setMaximumSize(QSize(16777215, 16777215))
        self.grp_list.setFont(font2)
#if QT_CONFIG(tooltip)
        self.grp_list.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.grp_list.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.grp_list.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.grp_list.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.grp_list.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.grp_list.setTitle(u"ACQUISITIONS")
        self.gridLayout_2 = QGridLayout(self.grp_list)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(9, 12, 9, -1)
        self.btn_delete = QPushButton(self.grp_list)
        self.btn_delete.setObjectName(u"btn_delete")
        self.btn_delete.setMinimumSize(QSize(0, 40))
        self.btn_delete.setMaximumSize(QSize(16777215, 40))
        font7 = QFont()
        font7.setFamilies([u"Tahoma"])
        font7.setPointSize(10)
        font7.setBold(True)
        self.btn_delete.setFont(font7)
#if QT_CONFIG(tooltip)
        self.btn_delete.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_delete.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_delete.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_delete.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_delete.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_delete.setText(u"DEL. VALUE")
#if QT_CONFIG(shortcut)
        self.btn_delete.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout_2.addWidget(self.btn_delete, 1, 1, 1, 1)

        self.btn_exit = QPushButton(self.grp_list)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setMinimumSize(QSize(0, 40))
        self.btn_exit.setMaximumSize(QSize(16777215, 40))
        self.btn_exit.setFont(font7)
#if QT_CONFIG(tooltip)
        self.btn_exit.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_exit.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_exit.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_exit.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_exit.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_exit.setText(u"SAVE & EXIT")
#if QT_CONFIG(shortcut)
        self.btn_exit.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout_2.addWidget(self.btn_exit, 1, 2, 1, 1)

        self.btn_left = QPushButton(self.grp_list)
        self.btn_left.setObjectName(u"btn_left")
        self.btn_left.setEnabled(False)
        self.btn_left.setMinimumSize(QSize(50, 40))
        self.btn_left.setMaximumSize(QSize(50, 40))
        font8 = QFont()
        font8.setFamilies([u"Arial Rounded MT Bold"])
        font8.setPointSize(11)
        font8.setBold(True)
        self.btn_left.setFont(font8)
#if QT_CONFIG(tooltip)
        self.btn_left.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_left.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_left.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_left.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_left.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_left.setText(u"<")
#if QT_CONFIG(shortcut)
        self.btn_left.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout_2.addWidget(self.btn_left, 1, 0, 1, 1)

        self.btn_right = QPushButton(self.grp_list)
        self.btn_right.setObjectName(u"btn_right")
        self.btn_right.setEnabled(False)
        self.btn_right.setMinimumSize(QSize(50, 40))
        self.btn_right.setMaximumSize(QSize(50, 40))
        self.btn_right.setFont(font8)
#if QT_CONFIG(tooltip)
        self.btn_right.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_right.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_right.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_right.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_right.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_right.setText(u">")
#if QT_CONFIG(shortcut)
        self.btn_right.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout_2.addWidget(self.btn_right, 1, 3, 1, 1)

        self.tbl_values = QTableWidget(self.grp_list)
        if (self.tbl_values.columnCount() < 2):
            self.tbl_values.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setText(u"TYPE");
        self.tbl_values.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setText(u"VALUE");
        self.tbl_values.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tbl_values.setObjectName(u"tbl_values")
        font9 = QFont()
        font9.setFamilies([u"Consolas"])
        font9.setPointSize(12)
        font9.setBold(False)
        self.tbl_values.setFont(font9)
#if QT_CONFIG(tooltip)
        self.tbl_values.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbl_values.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.tbl_values.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tbl_values.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tbl_values.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tbl_values.setAlternatingRowColors(True)
        self.tbl_values.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tbl_values.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tbl_values.horizontalHeader().setMinimumSectionSize(25)
        self.tbl_values.horizontalHeader().setDefaultSectionSize(100)
        self.tbl_values.verticalHeader().setVisible(False)
        self.tbl_values.verticalHeader().setMinimumSectionSize(35)
        self.tbl_values.verticalHeader().setDefaultSectionSize(35)
        self.tbl_values.verticalHeader().setHighlightSections(True)

        self.gridLayout_2.addWidget(self.tbl_values, 0, 0, 1, 4)


        self.verticalLayout.addWidget(self.grp_list)

        QWidget.setTabOrder(self.tx_value, self.btn_addvalue)
        QWidget.setTabOrder(self.btn_addvalue, self.btn_right)
        QWidget.setTabOrder(self.btn_right, self.btn_exit)
        QWidget.setTabOrder(self.btn_exit, self.cb_type)
        QWidget.setTabOrder(self.cb_type, self.cb_units)
        QWidget.setTabOrder(self.cb_units, self.btn_left)
        QWidget.setTabOrder(self.btn_left, self.tbl_values)
        QWidget.setTabOrder(self.tbl_values, self.btn_delete)
        QWidget.setTabOrder(self.btn_delete, self.tx_info)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"ACQUISITIONS", None))
    # retranslateUi

