# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QTABLE_DICT.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QDialog,
    QGridLayout, QHeaderView, QPushButton, QSizePolicy,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(500, 400)
        Dialog.setMinimumSize(QSize(350, 350))
        font = QFont()
        font.setFamilies([u"Arial Rounded MT Bold"])
        Dialog.setFont(font)
        Dialog.setWindowTitle(u"INPUT FORM")
#if QT_CONFIG(tooltip)
        Dialog.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        Dialog.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        Dialog.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        Dialog.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        Dialog.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        Dialog.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        Dialog.setWindowFilePath(u"")
        self.gridLayout = QGridLayout(Dialog)
        self.gridLayout.setObjectName(u"gridLayout")
        self.btn_row_add = QPushButton(Dialog)
        self.btn_row_add.setObjectName(u"btn_row_add")
        self.btn_row_add.setEnabled(True)
        self.btn_row_add.setMinimumSize(QSize(0, 35))
        self.btn_row_add.setMaximumSize(QSize(16777215, 35))
        font1 = QFont()
        font1.setFamilies([u"Arial Rounded MT Bold"])
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setItalic(False)
        self.btn_row_add.setFont(font1)
#if QT_CONFIG(tooltip)
        self.btn_row_add.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_row_add.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_row_add.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_row_add.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_row_add.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_row_add.setText(u"ADD ROW")
#if QT_CONFIG(shortcut)
        self.btn_row_add.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout.addWidget(self.btn_row_add, 0, 0, 1, 1)

        self.btn_row_del = QPushButton(Dialog)
        self.btn_row_del.setObjectName(u"btn_row_del")
        self.btn_row_del.setEnabled(True)
        self.btn_row_del.setMinimumSize(QSize(0, 35))
        self.btn_row_del.setMaximumSize(QSize(16777215, 35))
        self.btn_row_del.setFont(font1)
#if QT_CONFIG(tooltip)
        self.btn_row_del.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_row_del.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_row_del.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_row_del.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_row_del.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_row_del.setText(u"DEL ROW")
#if QT_CONFIG(shortcut)
        self.btn_row_del.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout.addWidget(self.btn_row_del, 0, 1, 1, 1)

        self.tbl_main = QTableWidget(Dialog)
        self.tbl_main.setObjectName(u"tbl_main")
        self.tbl_main.setEnabled(True)
        font2 = QFont()
        font2.setFamilies([u"Arial Rounded MT Bold"])
        font2.setPointSize(10)
        self.tbl_main.setFont(font2)
#if QT_CONFIG(tooltip)
        self.tbl_main.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbl_main.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.tbl_main.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tbl_main.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tbl_main.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tbl_main.setStyleSheet(u"background-color: rgb(228, 228, 228);")
        self.tbl_main.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tbl_main.setDragEnabled(False)
        self.tbl_main.setDragDropOverwriteMode(False)
        self.tbl_main.setDragDropMode(QAbstractItemView.NoDragDrop)
        self.tbl_main.setAlternatingRowColors(True)
        self.tbl_main.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tbl_main.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.tbl_main.horizontalHeader().setMinimumSectionSize(25)
        self.tbl_main.horizontalHeader().setDefaultSectionSize(160)
        self.tbl_main.verticalHeader().setVisible(False)
        self.tbl_main.verticalHeader().setMinimumSectionSize(35)
        self.tbl_main.verticalHeader().setDefaultSectionSize(35)

        self.gridLayout.addWidget(self.tbl_main, 1, 0, 1, 2)

        self.btn_save = QPushButton(Dialog)
        self.btn_save.setObjectName(u"btn_save")
        sizePolicy = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QSize(0, 60))
        self.btn_save.setMaximumSize(QSize(16777215, 60))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(True)
        self.btn_save.setFont(font3)
#if QT_CONFIG(tooltip)
        self.btn_save.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btn_save.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btn_save.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btn_save.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btn_save.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.btn_save.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.btn_save.setText(u"SAVE DATA")
#if QT_CONFIG(shortcut)
        self.btn_save.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.gridLayout.addWidget(self.btn_save, 2, 0, 1, 2)


        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        pass
    # retranslateUi

